// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuministrosDelEste.Infrastructure.Persistence.Context;

#nullable disable

namespace SuministrosDelEste.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SuministrosDelEste.Domain.Aggregates.Material.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nombre");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("PrecioUnitario");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("StockActual");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("StockMinimo");

                    b.HasKey("MaterialId");

                    b.ToTable("Materiales", (string)null);
                });

            modelBuilder.Entity("SuministrosDelEste.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContenidoJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Intentos")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OcurridoEn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcesadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcesadoEn");

                    b.ToTable("OutboxMessages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
